before:
  hooks:
    # You may remove this if you don't use go modules.
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - freebsd
  - windows
  goarch:
  - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
    freebsd: FreeBSD
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
